language: node_js
sudo: 'false'
before_script: []
env:
  global:
    - secure: >-
        gXBf+iqUUZrocSGfcRTaserS3FP+wmUgorkWJdrSf9Mm+TM+GTT7xSaZm0Dx1m8FH5sQP0CkYLYr36hb0dx7UzQgK1OzW6MqCVxo8c89qavWma/ykR80VpNdLU+RX2wqh5Qf/zFdVbY/qCeKIUb05bCydh8gE2h2/EvwdoK5StEy0mtbfrcsaGStviXM7vei833YsEmZb4UuzLBgF+nJe7yuVEDToqcapH/8bsgOIgCeAD0DX2x1c5/mVYRCvE0evLUGEAVFXeBkU1DGq4mWU8ssdf1hAjkWo2Irho1Z93sC/ACQTzdWtMS3fuANA/KxRCw1QfL7ffsWmKCoO+GYWd7jpK8tyuiHr7VqtmDBmRZC9jt/DQ0UMcEG1SUFCZgc6dFe8W5GOVXQvNhQ9/8+WFT1Q2afpPYlcldafy4CFfm1ovzSF2IBJjKO3cBlqdkiAlK3Nfjo9OzTqCtt+ylJXZ8tnWIr1iewBdjss1kNXDRU0LNqtFD8i9bfKa/kEgF188xQhKTShG3RSbNW8fG5IGsXWtBAohDVX+xtRXXqQJSP9VzyQUgBPLfheEEAMNptLIjaD2r/zMbEXoKVKhgVEK59cIvckRczO4oPAKQ1jLyMftVng+LW9j0Vqz7Ox6TwS7Fo+RrH1NS1VOob1HaRyNaC8juOV7fLPw/Vity2QJ4=
    - secure: >-
        RJaWTqeSodvjbzeSzaxOCaRsAzqh2Q8+XR5h+BrFrDAqwq5ujYhyQfnn1rQt51aJxBwDv6ZFB4krkK0lNXRDBmnYrjTP6pazZn2FLY2V+uTA3m0uwljTP6F3JvNF5kQurzY6E6S0SW1Whcm3Wt8SC7xv2P6AcZ+3+r2LKE6+FbTuM8f1i4jwBLOBdrsRI1xLFn2FBK7TAYJ1QIsx37Y2R8vLTntW9Dqt9avLVK2xM0kVRg2B+lpWgQQWgMpcLAYH+3NP0JQoCdt4gWh0EFcnA+GjgjaWcLxQtR5anwEgqUkbB1gHYICJqLeFLLER5lU8/zvypjPeXTNVWxkJZdS9X/fljdsh7AmtRO2SNKUV79hRau7N+RGwK6EvLSJl7ebdRZBmppMS86uUUvfVh18xzEtEIwpMjttuIqccjrhlliM1dsNx8hfD+TSqBk73BHhguZBuBC/riKA+kd9akf5a6uOUxEaQ3JVN6UGXg59slPFKgGdddI0kAnyla8z2rpNFyb2x0qm4UqQErHvyfTM+uefRqEyZAe7MpCnlwktmbgBh5SV7kKZkQFN0AAEieGhoHDKA0hQjbf08xiaihdno6Ltr0EcETVqNBv3tgfvmZkMDQMjerAVLCaTzdraBIp00PiZy51nIWR5Vcgnv6Xls1gTmCIJF2wQTj7OJzH5/kUI=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
